import { PagesPage } from './pages';

describe('2e2 ghost app', () => {
  beforeEach(() => {

    cy.visit('http://localhost:2369/ghost/#/signin')
    cy.get('form').within(() => {
            cy.get('#ember7').type(Cypress.env('username'))
            cy.get('#ember9').type(Cypress.env('password'))
            cy.get('#ember11').click()
            cy.wait(3000)
        })
  })
  
  it('test create new page', () => {
    cy.get('#ember28').click()
    cy.wait(2000)
    cy.get('.view-actions > a').click()
    cy.wait(2000)
    cy.get('textarea').type('Test Page')
    cy.get('div.koenig-editor__editor-wrapper').type('This is a test page created by Cypress.')
    cy.wait(1000)
    cy.get('div.ember-view span').click()
    cy.wait(1000)
    cy.get('button.gh-publishmenu-button span').click()
    cy.wait(1000)
    cy.get('.gh-btn-outline').click()
    cy.wait(1000)
    cy.get('div.ml3 > a').click()
    cy.wait(1000)
    expect(cy.get('h3').contains('Test Page')).to.exist
    cy.wait(2000)
  })
  
  it('test unpublish a published page', () => {
    cy.get('#ember28').click()
    cy.wait(2000)
    cy.get('.view-actions > a').click()
    cy.wait(2000)
    cy.get('textarea').type('Published Page')
    cy.get('div.koenig-editor__editor-wrapper').type('This is a published page created by Cypress.')
    cy.wait(1000)
    cy.get('div.ember-view span').click()
    cy.wait(1000)
    cy.get('button.gh-publishmenu-button span').click()
    cy.wait(1000)
    cy.get('.gh-btn-outline').click()
    cy.wait(1000)
    cy.get('div.ml3 > a').click()
    cy.wait(2000)
    
    cy.get('li.gh-posts-list-item > a').first().click()
    cy.wait(1000)
    cy.get('div.ember-view span').click()
    cy.wait(1000)
    cy.get('div.gh-publishmenu-radio-button').first().click()
    cy.wait(1000)
    cy.get('button.gh-publishmenu-button span').click()
    cy.wait(1000)
    cy.get('div.ml3 > a').click()
    cy.wait(1000)
    expect(cy.get('span.gh-badge-pink').contains('Draft')).to.exist
    cy.wait(2000)
  })
  
  it('test create and edit page', () => {
    // https://on.cypress.io/type
    cy.get('#ember28').click()
    cy.wait(2000)
    cy.get('.view-actions > a').click()
    cy.wait(2000)
    cy.get('textarea').type('Editable Page')
    cy.get('div.koenig-editor__editor-wrapper').type('This is an editable page created by Cypress.')
    cy.wait(1000)
    cy.get('div.ember-view span').click()
    cy.wait(1000)
    cy.get('button.gh-publishmenu-button span').click()
    cy.wait(1000)
    cy.get('.gh-btn-outline').click()
    cy.wait(1000)
    cy.get('div.ml3 > a').click()
    cy.wait(1000)
    
    cy.get('li.gh-posts-list-item > a').first().click()
    cy.wait(1000)
    cy.get('textarea').clear().type('Edited Page')
    cy.wait(1000)
    cy.get('div.koenig-editor__editor-wrapper').clear().type('This is an edited page created by Cypress.')
    cy.get('div.ember-view span').click()
    cy.wait(1000)
    cy.get('button.gh-publishmenu-button span').click()
    cy.wait(1000)
    cy.get('.gh-btn-outline').click()
    cy.wait(1000)
    cy.get('div.ml3 > a').click()
    cy.wait(1000)
    
    expect(cy.get('h3').contains('Edited Page')).to.exist
    cy.wait(2000)
  })
  
  it('test create delete page', () => {
    cy.get('#ember28').click()
    cy.wait(2000)
    cy.get('.view-actions > a').click()
    cy.wait(2000)
    cy.get('textarea').type('Deletable Page')
    cy.get('div.koenig-editor__editor-wrapper').type('This is a deletable page created by Cypress.')
    cy.wait(1000)
    cy.get('div.ember-view span').click()
    cy.wait(1000)
    cy.get('button.gh-publishmenu-button span').click()
    cy.wait(1000)
    cy.get('.gh-btn-outline').click()
    cy.wait(1000)
    cy.get('div.ml3 > a').click()
    cy.wait(1000)
    
    cy.get('li.gh-posts-list-item > a').first().click()
    cy.wait(1000)
    cy.get('.settings-menu-toggle > span').click()
    cy.wait(1000)
    cy.get('.settings-menu-delete-button > span').click()
    cy.wait(1000)
    cy.get('.gh-btn-red > span').click()
    cy.wait(1000)
    cy.get('h3').contains('Deletable Page').should('not.exist')
  })
})
